[project]
name = "PersonalAssistantProj1_Eecs449"
default-app = "web"
jac-version = "==0.37.23"

[apps]
[apps.web]
kind = "web-app"
entry-point = "web.main"

[apps.planner]
kind = "service"
entry-point = "core.planner"

[apps.mobile]
kind = "mobile"
entry-point = "mobile.main"

[apps.cli]
kind = "cli"
entry-point = "cli.main"

[apps.cli.check]
[apps.cli.check.lint]
ignore = ["no-print"]

[test]
directories = ["core", "cli"]

[dependencies]
[dependencies.npm]
react-native-web = "^0.21.2"
